version: '3.7'

services:
  elastic-manager:
    #    image: test-app-light
    #    build:
    #      context: .
    image: elastic-manager:v1.0.0
    volumes:
      - ./src:/src
    ports:
      - 3000:8080